# Generated by Django 4.1.1 on 2022-09-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
